### ISSUE TITLE
Add Select Insection button to Dash Frag

### ISSUE THREAD

**Issue by zxkevinxz** [zxkevinxz/Foundations#70]
As a user, I want a select inspection button on the dash fragment. You select one of the recent inspections, and then the button uses fragmentSwitch.setCurrentReport() and passes in currentReport, and then uses fragment switcher to load the NewInspection fragment.

**Comment by 1jc** [comment]
I'll take a look at it
 *Joette Damo*

Guilt and resentment are two causes for lack of joy!
