### ISSUE TITLE
Inspector Profile Selection Page

### ISSUE THREAD

**Issue by 1jc** [zxkevinxz/Foundations#8]
Create user story which displays available inspectors for a project.  A simple page demo.   Joette Damo

**Comment by zxkevinxz** [comment]
As a user, I will see a page that shows available profiles, and has a button to add a new profile.

![Screen Shot 2020-10-06 at 6 48 05 PM](https://user-images.githubusercontent.com/22699679/95389797-35339400-08a9-11eb-8cc5-3728eaa8f107.png)
